#!/usr/bin/env bash

OTEL_SERVICE_NAME=${WORKLOAD_NAME:-${SERVICE_NAME}}
OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://tempo:4317}
OTEL_RESOURCE_ATTRIBUTES=${OTEL_RESOURCE_ATTRIBUTES:-service.name=${OTEL_SERVICE_NAME},k8s_app=${K8S_APP}}
OTEL_AGENT_VERSION=${OTEL_AGENT_VERSION:-v1.24.0}
OTEL_AGENT_PATH=/app/agent

export JAVA_OPTS="$JAVA_OPTS -javaagent:${OTEL_AGENT_PATH}/opentelemetry-javaagent-${OTEL_AGENT_VERSION}.jar"
